- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
   - name: Install mysql server 
     ansible.builtin.package:
       name: mysql-server
       state: installed

   - name: Start enable mysql server service    
     ansible.builtin.service: 
       name: mysqld
       state: started 
       enabled: yes 

   - name: Collect all info except settings and users by root
     community.mysql.mysql_info:
        login_user: root
        login_password: ExpenseApp@1 
        login_host: mysql.ganeshdevops.online

   - name: Print the mysql output 
     ansible.builtin.debug:
         msg: "My SQL info; {{ mysql_info }}"